version: '3.4'

services:
  weirdflex.api:
    image: ${DOCKER_REGISTRY-}weirdflexapi
    build:
      context: .
      dockerfile: src/WeirdFlex.Api/Dockerfile
    environment:
    - ConnectionStrings__FlexContext=Server=weirdflex-sqlserver;Database=flexDb;User=sa;Password=Your_password123;      
    depends_on:
    - weirdflex_sqlserver

  weirdflex_sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: weirdflex-sqlserver
    ports:
    - 1433:1433
    environment:
    - SA_PASSWORD=Your_password123
    - ACCEPT_EULA=Y
    - MSSQL_PID=Express