name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore WeirdFlex.sln
    - name: Build
      run: dotnet build WeirdFlex.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test WeirdFlex.sln --no-restore --verbosity normal
